insert into public.challenges(day_number,day_name,title,subtitle,description,wellness_message,instructions,order_number,form_fields) values
(1,'Lunes','Conocernos un poco más','Mascotas de la infancia','Una pequeña historia puede ser el inicio de una gran conexión.','Conectar empieza con una buena conversación.','Descubrí el nombre de la mascota de la infancia de 3 compañeros(as).',1,'[{"key":"name1","label":"Nombre del compañero 1"},{"key":"pet1","label":"Nombre de su mascota"},{"key":"name2","label":"Nombre del compañero 2"},{"key":"pet2","label":"Nombre de su mascota"},{"key":"name3","label":"Nombre del compañero 3"},{"key":"pet3","label":"Nombre de su mascota"}]'),
(2,'Martes','Un detalle inesperado','Detalle sorpresa','El detalle no tiene que tener valor económico. Puede ser una nota, un chocolate, un café o algún gesto simbólico.','Los pequeños gestos hacen grandes diferencias.','Entregá un pequeño detalle sorpresa a un compañero(a) de otro departamento al que vos pertenecés.',2,'[{"key":"name","label":"Nombre del compañero"},{"key":"department","label":"Departamento"},{"key":"detail","label":"Breve descripción del detalle","multiline":true}]'),
(3,'Miércoles','Reconocé algo positivo','Reconocimiento','Tomate un momento para reconocer lo que hace especial a alguien.','Lo que valorás también merece ser dicho.','Elegí una persona con la que normalmente no trabajás directamente y decile algo que valorás de su trabajo o de su forma de ser.',3,'[{"key":"name","label":"Nombre del compañero"},{"key":"recognition","label":"¿Qué valorás de esa persona?","multiline":true}]'),
(4,'Jueves','Descubrí un talento','Talentos ocultos','Hay mucho por descubrir detrás de cada compañero.','Compartir lo que nos apasiona nos acerca.','Descubrí una habilidad, hobby o talento de 2 compañeros(as) de áreas distintas.',4,'[{"key":"name1","label":"Nombre del compañero 1"},{"key":"area1","label":"Área o departamento 1"},{"key":"talent1","label":"Hobby, talento o habilidad 1"},{"key":"name2","label":"Nombre del compañero 2"},{"key":"area2","label":"Área o departamento 2"},{"key":"talent2","label":"Hobby, talento o habilidad 2"}]'),
(5,'Viernes','Bingo Humano','Descubrí quién es quién','Completá las nueve casillas con nueve compañeros diferentes.','Somos un equipo de historias únicas.','Encontrá un compañero que cumpla cada característica. No se puede utilizar el mismo compañero en más de una casilla.',5,'[]')
on conflict(day_number) do nothing;

insert into public.bingo_items(challenge_id,description,order_number)
select c.id,v.description,v.n from public.challenges c cross join (values
(1,'Tiene más de 5 años en COOPEBANACIO.'),(2,'Tiene una mascota.'),(3,'Practica algún deporte.'),
(4,'Tiene un hobby artístico.'),(5,'Ha trabajado en más de un área.'),(6,'Prefiere montaña antes que playa.'),
(7,'Toma café todos los días.'),(8,'Ha viajado fuera del país este año.'),(9,'Cumple años en el mismo semestre que vos.')
) as v(n,description) where c.day_number=5 on conflict(challenge_id,order_number) do nothing;
