'use client';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { LockKeyholeOpen, ChartNoAxesCombined, NotebookPen, Users, LogOut, Search, Download, ShieldCheck } from 'lucide-react';
import { allRows, configured, db } from '@/lib/supabase';
import { downloadCsv, formatDate, friendlyError } from '@/lib/helpers';
import type { BingoItem, Challenge, Participant, Response, UnlockEvent } from '@/lib/types';
import { Brand, Loading, Modal, Notice, StateBadge } from './ui';
import { Captcha } from './captcha';
const sections=[{id:'desbloqueo',name:'Desbloqueo',icon:LockKeyholeOpen},{id:'reportes',name:'Reportes',icon:ChartNoAxesCombined},{id:'retos',name:'Retos',icon:NotebookPen},{id:'participantes',name:'Participantes',icon:Users}];
export default function AdminApp({section='desbloqueo'}:{section?:string}) {
 const router=useRouter();
 const [authorized,setAuthorized]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState('');
 const [participants,setParticipants]=useState<Participant[]>([]),[challenges,setChallenges]=useState<Challenge[]>([]),[responses,setResponses]=useState<Response[]>([]),[bingo,setBingo]=useState<BingoItem[]>([]),[events,setEvents]=useState<UnlockEvent[]>([]),[search,setSearch]=useState(''),[detail,setDetail]=useState<Participant|null>(null),[editing,setEditing]=useState<Challenge|null>(null),[draftBingo,setDraftBingo]=useState<BingoItem[]>([]);
 const load=useCallback(async()=>{
  const {data:{session}}=await db().auth.getSession();if(!session){setAuthorized(false);return;}
  const {data,error}=await db().rpc('is_admin');if(error)throw error;if(!data){setAuthorized(false);return;}setAuthorized(true);
  const result=await Promise.all([allRows<Participant>('participants'),allRows<Challenge>('challenges'),allRows<Response>('challenge_responses'),allRows<BingoItem>('bingo_items'),allRows<UnlockEvent>('unlock_events')]);
  setParticipants(result[0].sort((a,b)=>a.full_name.localeCompare(b.full_name,'es')));setChallenges(result[1].sort((a,b)=>a.order_number-b.order_number));setResponses(result[2]);setBingo(result[3].sort((a,b)=>a.order_number-b.order_number));setEvents(result[4].sort((a,b)=>b.occurred_at.localeCompare(a.occurred_at)));
 },[]);
 useEffect(()=>{if(!configured()){setLoading(false);return;}load().catch(e=>setError(friendlyError(e))).finally(()=>setLoading(false));const {data:{subscription}}=db().auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){setAuthorized(false);setParticipants([]);setResponses([]);setDetail(null);setEditing(null);}});return()=>subscription.unsubscribe();},[load]);
 const count=(id:string)=>responses.filter(r=>r.participant_id===id).length;
 async function signIn(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const {error}=await db().auth.signInWithPassword({email,password,options:{captchaToken:token||undefined}});setPassword('');if(error)setError('No pudimos iniciar sesión. Revisá tus credenciales o intentá más tarde.');else{const {data,error:roleError}=await db().rpc('is_admin');if(roleError||!data){await db().auth.signOut({scope:'local'});setError('Esta cuenta no tiene acceso administrativo.');}else{try{await load();router.replace('/admin/'+section);}catch(e){setError(friendlyError(e));}}}setBusy(false);}
 async function mutate(operation:()=>PromiseLike<{error:unknown}>,success:string){setBusy(true);setError('');setMessage('');try{const {error}=await operation();if(error)throw error;await load();setMessage(success);}catch(e){setError(friendlyError(e));}finally{setBusy(false);}}
 async function saveChallenge(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;setBusy(true);setError('');const {error}=await db().rpc('edit_challenge',{p_id:editing.id,p_title:editing.title,p_description:editing.description,p_message:editing.wellness_message,p_instructions:editing.instructions,p_bingo:draftBingo.map(i=>({id:i.id,description:i.description}))});if(error){setError(friendlyError(error));setBusy(false);return;}setEditing(null);try{await load();setMessage('Reto actualizado.');}catch(e){setError(friendlyError(e));}setBusy(false);}
 function exportParticipants(onlyFinished=false){downloadCsv(onlyFinished?'participantes-5-de-5.csv':'participantes.csv',[
  ['Nombre completo','Cédula','Fecha de registro','Último acceso','Retos completados','Progreso','Estado'],
  ...participants.filter(p=>!onlyFinished||count(p.id)===5).map(p=>[p.full_name,p.identification,formatDate(p.created_at),formatDate(p.last_login),count(p.id),`${count(p.id)*20}%`,p.active?'Activo':'Inactivo'])
 ]);}
 function exportAnswers(){downloadCsv('respuestas.csv',[['Participante','Cédula','Reto','Fecha y hora','Pregunta','Respuesta'],...responses.flatMap(r=>{const p=participants.find(p=>p.id===r.participant_id);return r.challenge_snapshot.fields.map(f=>[p?.full_name,p?.identification,r.challenge_snapshot.title,formatDate(r.completed_at),f.label,r.response_data[f.key]])})]);}
 if(loading)return <><header className="topbar"><Brand/></header><Loading/></>;
 if(!authorized)return <><header className="topbar"><Brand/><a className="text-button" href="/">Ingreso de colaboradores</a></header><main id="main" className="admin-login glass"><ShieldCheck className="admin-shield" size={36}/><p className="eyebrow">SOLO PERSONAS AUTORIZADAS</p><h1>Administración</h1><p className="muted">Un espacio para acompañar la semana de bienestar.</p>{!configured()&&<Notice>El acceso estará disponible al finalizar la configuración.</Notice>}{error&&<Notice error>{error}</Notice>}<form onSubmit={signIn}><label>Correo electrónico<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><Captcha onToken={setToken}/><button className="primary wide" disabled={busy||!configured()||(!!process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY&&!token)}>{busy?'Verificando…':'Ingresar a administración'}</button></form></main></>;
 const current=sections.find(s=>s.id===section)??sections[0];
 const filtered=participants.filter(p=>p.full_name.toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es'))||p.identification.includes(search.replace(/[-\s]/g,'')));
 return <><header className="topbar"><Brand/><div className="user"><span className="badge">Administración</span><button className="text-button" onClick={async()=>{const {error}=await db().auth.signOut({scope:'local'});if(error)setError(friendlyError(error));else setAuthorized(false);}}><LogOut size={17}/> Salir</button></div></header><div className="admin-layout"><aside><p className="eyebrow">SEMANA DEL BIENESTAR</p><nav aria-label="Administración">{sections.map(s=><a key={s.id} href={'/admin/'+s.id} className={section===s.id?'active':''} aria-current={section===s.id?'page':undefined}><s.icon size={20}/>{s.name}</a>)}</nav><div className="sidebar-note"><ShieldCheck/><p>Cuidamos cada dato.<br/>Conectamos a cada persona.</p></div></aside><main id="main" className="admin-main"><div className="section-heading"><div><p className="eyebrow">ADMINISTRACIÓN</p><h1>{current.name}</h1></div><button className="secondary" disabled={busy} onClick={()=>{setBusy(true);load().then(()=>setMessage('Datos actualizados.')).catch(e=>setError(friendlyError(e))).finally(()=>setBusy(false));}}>Actualizar</button></div>{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}
 {section==='desbloqueo'&&<><p className="muted">Vos marcás el ritmo. Habilitá los retos para todo el equipo.</p><div className="unlock-list">{challenges.map(c=><article className="panel unlock-row" key={c.id}><div className={`day-number tone-${c.day_number}`}>0{c.day_number}</div><div className="grow"><h3>{c.day_name}</h3><p>{c.title}</p><small>Último desbloqueo: {formatDate(c.unlocked_at)}</small></div><StateBadge completed={false} unlocked={c.unlocked}/><button className={`toggle ${c.unlocked?'on':''}`} role="switch" aria-checked={c.unlocked} aria-label={`${c.day_name}: ${c.unlocked?'desbloqueado':'bloqueado'}`} disabled={busy} onClick={()=>mutate(()=>db().from('challenges').update({unlocked:!c.unlocked}).eq('id',c.id),c.unlocked?'Reto bloqueado.':'Reto disponible para todos los colaboradores.')}><span/></button></article>)}</div><h2 className="subheading">Historial de cambios</h2>{events.length===0?<p className="muted">Todavía no se han desbloqueado retos.</p>:<div className="table-wrap"><table><thead><tr><th>Día</th><th>Acción</th><th>Fecha y hora</th><th>Administrador (ID)</th></tr></thead><tbody>{events.slice(0,50).map(e=><tr key={e.id}><td>{challenges.find(c=>c.id===e.challenge_id)?.day_name}</td><td>{e.unlocked?'Desbloqueado':'Bloqueado'}</td><td>{formatDate(e.occurred_at)}</td><td className="small">{e.admin_id}</td></tr>)}</tbody></table></div>}</>}
 {section==='reportes'&&<><p className="muted">Así avanza nuestra semana de bienestar.</p><div className="metrics">{[['Total de participantes',participants.length],['Participantes activos',participants.filter(p=>p.active).length],['Retos completados',responses.length],['Promedio por participante',participants.length?(responses.length/participants.length).toFixed(1):'0'],['Personas con 5/5',participants.filter(p=>count(p.id)===5).length]].map(([label,value])=><article className="panel metric" key={label}><span>{label}</span><strong>{value}</strong></article>)}</div><p className="small muted">Activo significa que el participante está habilitado para ingresar. Las cifras incluyen todas las inscripciones de esta actividad.</p><section className="panel report-chart"><h2>Participación por reto</h2>{challenges.map(c=>{const total=responses.filter(r=>r.challenge_id===c.id).length;return <div className="bar-row" key={c.id}><span>{c.day_name}<small>{c.title}</small></span><progress className={`tone-${c.day_number}`} value={total} max={Math.max(participants.length,1)} aria-label={`${c.title}: ${total} completados`}/><strong>{total}</strong></div>})}</section><section className="panel"><h2>Exportar resultados</h2><p className="muted">Archivos CSV compatibles con Excel. Contienen información privada de los participantes.</p><div className="button-row"><button className="secondary" onClick={()=>exportParticipants()}><Download size={17}/> Participantes</button><button className="secondary" onClick={exportAnswers}><Download size={17}/> Respuestas</button><button className="primary" onClick={()=>exportParticipants(true)}><Download size={17}/> Exportar participantes que completaron 5/5</button></div></section></>}
 {section==='retos'&&<><p className="muted">Personalizá los mensajes y las instrucciones de cada día.</p><div className="challenge-editor-list">{challenges.map(c=><article className="panel" key={c.id}><div className="section-heading"><span className="eyebrow">{c.day_name} · RETO {c.day_number}</span><StateBadge completed={false} unlocked={c.unlocked}/></div><h2>{c.title}</h2><p>{c.instructions}</p><p className="quote">{c.wellness_message}</p><button className="secondary" onClick={()=>{setEditing({...c});setDraftBingo(bingo.filter(i=>i.challenge_id===c.id).map(i=>({...i})));setError('');}}>Editar reto</button></article>)}</div></>}
 {section==='participantes'&&<><div className="participants-toolbar"><label className="search-label"><Search size={18}/><input aria-label="Buscar por nombre o cédula" placeholder="Buscar por nombre o cédula" value={search} onChange={e=>setSearch(e.target.value)}/></label><span className="muted">{filtered.length} participantes</span></div><div className="table-wrap"><table><thead><tr><th>Nombre completo</th><th>Cédula</th><th>Registro</th><th>Último acceso</th><th>Retos</th><th>Progreso</th><th>Estado</th><th>Detalle</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><strong>{p.full_name}</strong></td><td>{p.identification}</td><td>{formatDate(p.created_at)}</td><td>{formatDate(p.last_login)}</td><td>{count(p.id)} / 5</td><td><progress max={5} value={count(p.id)} aria-label={`Progreso de ${p.full_name}`}/><small>{count(p.id)*20}%</small></td><td>{p.active?'Activo':'Inactivo'}</td><td><button className="text-button" onClick={()=>setDetail(p)}>Ver respuestas<span className="sr-only"> de {p.full_name}</span></button></td></tr>)}</tbody></table>{filtered.length===0&&<p className="empty">{search?'No encontramos participantes con esos datos.':'Las personas aparecerán aquí cuando se inscriban.'}</p>}</div></>}
 </main></div>{editing&&<Modal title="Editar reto" onClose={()=>{if(!busy)setEditing(null);}}><p className="eyebrow">{editing.day_name}</p><h2>Editar reto</h2>{error&&<Notice error>{error}</Notice>}<form onSubmit={saveChallenge}>{([{key:'title',label:'Título',max:160},{key:'description',label:'Descripción',max:4000},{key:'wellness_message',label:'Mensaje de bienestar',max:1000},{key:'instructions',label:'Instrucciones',max:4000}] as const).map(f=><label key={f.key}>{f.label}<textarea required={f.key==='title'||f.key==='instructions'} maxLength={f.max} rows={f.key==='title'?1:3} value={editing[f.key]} onChange={e=>setEditing({...editing,[f.key]:e.target.value})}/></label>)}{editing.day_number===5&&<fieldset><legend>Criterios del Bingo Humano</legend>{draftBingo.map((item,i)=><label key={item.id}>Casilla {i+1}<input required maxLength={240} value={item.description} onChange={e=>setDraftBingo(draftBingo.map(x=>x.id===item.id?{...x,description:e.target.value}:x))}/></label>)}</fieldset>}<button className="primary wide" disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button></form></Modal>}{detail&&<Modal title={detail.full_name} onClose={()=>setDetail(null)}><p className="eyebrow">PARTICIPANTE</p><h2>{detail.full_name}</h2><dl className="detail-meta"><div><dt>Cédula</dt><dd>{detail.identification}</dd></div><div><dt>Registro</dt><dd>{formatDate(detail.created_at)}</dd></div><div><dt>Último acceso</dt><dd>{formatDate(detail.last_login)}</dd></div><div><dt>Progreso</dt><dd>{count(detail.id)} de 5 · {count(detail.id)*20}%</dd></div></dl><button className="secondary" disabled={busy} onClick={()=>mutate(async()=>{const result=await db().from('participants').update({active:!detail.active}).eq('id',detail.id);if(!result.error)setDetail({...detail,active:!detail.active});return result;},'Estado del participante actualizado.')}>{detail.active?'Desactivar participante':'Activar participante'}</button>{responses.filter(r=>r.participant_id===detail.id).length===0&&<p className="empty">Todavía no ha completado retos.</p>}{responses.filter(r=>r.participant_id===detail.id).sort((a,b)=>a.completed_at.localeCompare(b.completed_at)).map(r=><article className="response-record" key={r.id}><h3>✅ {r.challenge_snapshot.title}</h3><small>{formatDate(r.completed_at)}</small><dl>{r.challenge_snapshot.fields.map(f=><div key={f.key}><dt>{f.label}</dt><dd>{r.response_data[f.key]}</dd></div>)}</dl></article>)}</Modal>}</>;
}
