'use client';
import { useEffect, useState } from 'react';
import { Check, Sparkles } from 'lucide-react';
import { db } from '@/lib/supabase';
import { formatDate, friendlyError, validateAnswers } from '@/lib/helpers';
import type { BingoItem, Challenge, Field, Response } from '@/lib/types';
import { Modal, Notice, Loading, StateBadge } from './ui';
export function ChallengeDialog({challenge,response,participantId,onClose,onCompleted}:{challenge:Challenge;response?:Response;participantId:string;onClose:()=>void;onCompleted:()=>Promise<void>}) {
 const [fields,setFields]=useState<Field[]>(response?.challenge_snapshot.fields??challenge.form_fields),[answers,setAnswers]=useState<Record<string,string>>(response?.response_data??{}),[loading,setLoading]=useState(!response&&challenge.day_number===5),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(response||challenge.day_number!==5)return;let live=true;db().from('bingo_items').select('*').eq('challenge_id',challenge.id).eq('active',true).order('order_number').then(({data,error})=>{if(!live)return;if(error||data?.length!==9)setError('No pudimos abrir el bingo. Cerrá esta ventana e intentá nuevamente.');else setFields((data as BingoItem[]).map(i=>({key:i.id,label:i.description})));setLoading(false);});return()=>{live=false;};},[challenge,response]);
 async function submit(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();const validation=validateAnswers(fields,answers,challenge.day_number===5);if(validation){setError(validation);return;}setBusy(true);setError('');const {error}=await db().from('challenge_responses').insert({participant_id:participantId,challenge_id:challenge.id,response_data:answers});if(error){setError(friendlyError(error));setBusy(false);}else await onCompleted();}
 return <Modal title={challenge.title} onClose={()=>{if(!busy)onClose();}}><div className={`day-icon tone-${challenge.day_number}`}><Sparkles/></div><p className="eyebrow">{challenge.day_name} · Reto {challenge.day_number}</p><h2>{response?.challenge_snapshot.title??challenge.title}</h2>{challenge.day_number===5&&<h3>Descubrí quién es quién</h3>}<StateBadge completed={!!response} unlocked={challenge.unlocked}/><p className="instruction">{response?.challenge_snapshot.instructions??challenge.instructions}</p>{!response&&<p className="muted">{challenge.description}</p>}{error&&<Notice error>{error}</Notice>}{loading?<Loading/>:<form onSubmit={submit}><div className={challenge.day_number===5?'bingo-grid':'form-grid'}>{fields.map((f,i)=><label className={challenge.day_number===5?'bingo-cell':''} key={f.key}>{challenge.day_number===5&&<span className="bingo-number">{String(i+1).padStart(2,'0')}</span>}<span>{f.label}</span>{response?<div className="saved-answer">{answers[f.key]}</div>:f.multiline?<textarea required maxLength={1000} rows={3} value={answers[f.key]??''} onChange={e=>setAnswers({...answers,[f.key]:e.target.value})}/>:<input required maxLength={1000} autoComplete="off" placeholder={challenge.day_number===5?'Nombre del compañero':'Escribí tu respuesta'} value={answers[f.key]??''} onChange={e=>setAnswers({...answers,[f.key]:e.target.value})}/>}</label>)}</div>{response?<p className="success-line"><Check size={18}/> Completado el {formatDate(response.completed_at)}</p>:<button className="primary wide" disabled={busy||loading||fields.length===0}>{busy?'Guardando…':'Completar reto'}<Check size={18}/></button>}</form>}</Modal>;
}
